[workspace]
members = [
  "cmd/pen",
  "lib/app",
  "lib/ast",
  "lib/ast-hir",
  "lib/core/ffi",
  "lib/ffi",
  "lib/ffi-macro",
  "lib/hir",
  "lib/hir-mir",
  "lib/infra",
  "lib/interface",
  "lib/mir",
  "lib/mir-fmm",
  "lib/parse",
  "lib/position",
  "lib/prelude/ffi",
  "lib/test-info",
]
exclude = ["cmd/test", "examples", "lib/core", "lib/os", "lib/os-sync", "tmp"]

[profile.release]
lto = true
