[package]
name = "os-app"
version = "0.1.0"
publish = false
edition = "2021"

[dependencies]
ffi = { package = "pen-ffi", version = "*", features = ["runtime"] }
futures = "0.3.21"
once_cell = "1"
tokio = { "version" = "1", features = ["full"] }
