[package]
name = "pen"
version = "0.3.9"
authors = ["Yota Toyama <raviqqe@gmail.com>"]
edition = "2021"

[dependencies]
clap = "3"
app = { path = "../../lib/app" }
indoc = "1"
infra = { path = "../../lib/infra" }
once_cell = "1"
url = "2"
