[package]
name = "pen"
version = "0.6.6"
authors = ["Yota Toyama <raviqqe@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "4", features = ["cargo"] }
app = { path = "../../lib/app" }
indoc = "2"
infra = { path = "../../lib/infra" }
once_cell = "1"
url = "2"
