[package]
name = "prelude"
version = "0.1.0"
publish = false
edition = "2021"

[lib]
name = "prelude"
crate-type = ["staticlib"]

[dependencies]
ffi = { package = "pen-ffi", "version" = "*" }
siphasher = "1.0"
